# Generated by Django 4.2.21 on 2025-05-23 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='stream_url',
        ),
    ]
